### ISSUE TITLE
[Suggestion] ICBM Classic support

### ISSUE THREAD

**Issue by xJon** [Invadermonky/JustEnoughMagiculture#13]
https://github.com/BuiltBrokenModding/ICBM-Classic/blob/prod/1.12/src/main/java/icbm/classic/ICBMClassic.java#L159-L204

**Comment by Invadermonky** [comment]
JER should support vanilla loot table changes by default, but for some reason it is not recognizing the changes ICBM is making. It looks like ICBM is loading after JER accesses the loot tables.

Unfortunately, due to some jank in JER code, there is no way to fix this without causing issues elsewhere.
