### ISSUE TITLE
Crash with Beast Slayer 2

### ISSUE THREAD

**Issue by xJon** [Invadermonky/JustEnoughMagiculture#7]
https://mclo.gs/F5NpiE6
Most likely due to the package path name changing to `beastslayer`.

**Comment by Invadermonky** [comment]
Pretty busy at the moment, but I'll check this out when I have time. Going to have to do some wonky stuff to make JEM compatible with the old version as well as the new version.

**Comment by xJon** [comment]
Very appreciated!

**Comment by Invadermonky** [comment]
Had some time and took a look at this issue. Because Beast Slayer is in an alpha release, I am going to hold off on this fix until at least a beta release.

There was a slight problem with the versioning in Beast Slayer 2.0 due to the mod incorrectly listing its version as 1.9.99999 despite the actual version being 2.0_test. Due to this, I cannot create an automated fix. For the time being, you will have to manually disable Beast Slayer integration in the JEM config to fix the crash when running it with Beast Slayer 2.0.

**Comment by xJon** [comment]
Beast Slayer 2 has been used in Hexxit II since September last year so it's definitely playable, but I understand holding off 👍

**Comment by Invadermonky** [comment]
It's mostly the issue of versioning. The 2.0 alpha release is using the incorrect version number in the mod registration which means I can't support both at the same time. JEM itself is set up to support both the 1.9 release and the 2.0 release but due to the versioning I cannot support both.

Because alpha releases do not show up normally in Curseforge searches, it is better to support the 1.9 beta version exclusively for the time being.

**Comment by xJon** [comment]
@Invadermonky It has been updated recently to Beta status.

**Comment by Invadermonky** [comment]
Integration added as of version [1.12.2-1.2.0](https://www.curseforge.com/minecraft/mc-mods/just-enough-magiculture/files/5787394)
